# Generated by Django 4.0.3 on 2022-07-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_song_collectionartistid'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='collectionArtistViewUrl',
            field=models.CharField(default='', max_length=200),
        ),
    ]
