from django.db import models

# Create your models here.


class Song(models.Model):
    wrapperType = models.CharField(max_length=200, default='')
    kind = models.CharField(max_length=200, default='')
    artistId = models.IntegerField(default=0)
    collectionId = models.IntegerField(default=0)
    trackId = models.IntegerField(default=0)
    collectionArtistId = models.IntegerField(default=0)
    artistName = models.CharField(max_length=200, default='')
    collectionName = models.CharField(max_length=200, default='')
    collectionArtistName = models.CharField(max_length=200, default='')
    trackName = models.CharField(max_length=200, default='')
    collectionCensoredName = models.CharField(max_length=200, default='')
    trackCensoredName = models.CharField(max_length=200, default='')
    artistViewUrl = models.CharField(max_length=200, default='')
    collectionViewUrl = models.CharField(max_length=200, default='')
    collectionArtistViewUrl = models.CharField(max_length=200, default='')
    trackViewUrl = models.CharField(max_length=200, default='')
    previewUrl = models.CharField(max_length=200, default='')
    artworkUrl30 = models.CharField(max_length=200, default='')
    artworkUrl60 = models.CharField(max_length=200, default='')
    artworkUrl100 = models.CharField(max_length=200, default='')
    collectionPrice = models.FloatField(default=0.0)
    trackPrice = models.FloatField(default=0.0)
    trackHdPrice = models.FloatField(default=0.0)
    trackHdRentalPrice = models.FloatField(default=0.0)
    trackRentalPrice = models.FloatField(default=0.0)
    collectionHdPrice = models.FloatField(default=0.0)
    releaseDate = models.CharField(max_length=200, default='')
    collectionExplicitness = models.CharField(max_length=200, default='')
    trackExplicitness = models.CharField(max_length=200, default='')
    discCount = models.IntegerField(default=1)
    discNumber = models.IntegerField(default=1)
    trackCount = models.IntegerField(default=1)
    trackNumber = models.IntegerField(default=1)
    trackTimeMillis = models.IntegerField(default=0)
    country = models.CharField(max_length=200, default='')
    longDescription = models.CharField(max_length=1000, default='')
    shortDescription = models.CharField(max_length=1000, default='')
    currency = models.CharField(max_length=200, default='')
    primaryGenreName = models.CharField(max_length=200, default='')
    isStreamable = models.BooleanField(default=False)
    contentAdvisoryRating = models.CharField(max_length=200, default='')
    hasITunesExtras = models.BooleanField(default=False)

    def __str__(self, default=''):
        return '{0} – {1}'.format(self.trackName, self.artistName)
